"""Self-coaching — the bot learns from its own (and back-tested) trades.

Three levels, all free (no paid broker / data feed needed):

  * Level 1 — performance memory: tracks realized win-rate & PnL per stock and
    turns it into a score multiplier, so names that keep winning get favoured
    and repeat losers get demoted. Pure experience.

  * Level 2 — adaptive exits: watches whether stops are being whipsawed (too many
    stop-loss exits vs take-profits) and widens/tightens the stop accordingly.

  * Level 3 — ML coach: a classifier trained on LABELLED trades. Training data is
    generated by replaying the entry setup over years of free historical price
    data for the underlying stocks (NVDA, TSLA, …) and labelling each as a win or
    loss via the same take-profit / stop-loss bracket the live bot uses. It then
    estimates the probability a NEW entry will win — used as an optional, soft
    entry filter (off by default so it never reduces trade count unless asked).

Everything degrades gracefully: no sklearn / no data → multipliers are neutral,
exits are unchanged, win-probability is None.
"""

from __future__ import annotations

import os
import time
from pathlib import Path

import market
import finnhub_data
from indicators import sma_series, rsi_series

HERE = Path(__file__).resolve().parent
MODELS_DIR = Path(os.environ.get("DATA_DIR", str(HERE))) / "models"

MIN_TRADES_FOR_WEIGHT = 4     # need this many closed trades before weighting a symbol
H = 8                         # forward bars to resolve a simulated trade
MIN_SAMPLES = 150             # min labelled examples to train the ML coach

try:
    import numpy as np
    from sklearn.ensemble import GradientBoostingClassifier
    HAVE_SK = True
except Exception:             # pragma: no cover
    HAVE_SK = False

_model = [None]               # [(classifier, n_samples)] or [None]


# ----------------------- Level 1: performance memory -----------------------
def record_outcome(state, symbol, pnl, reason):
    """Update per-symbol win/loss memory and exit-reason stats on every close."""
    perf = state.setdefault("perf", {})
    s = perf.setdefault(symbol, {"wins": 0, "losses": 0, "pnl": 0.0})
    if pnl > 0:
        s["wins"] += 1
    else:
        s["losses"] += 1
    s["pnl"] = round(s["pnl"] + pnl, 4)
    ex = state.setdefault("exit_stats",
                          {"stop": 0, "tp": 0, "trend": 0, "session": 0, "other": 0})
    r = (reason or "").lower()
    key = ("stop" if "stop-loss" in r else "tp" if "take-profit" in r
           else "trend" if "trend" in r else "session" if "session" in r else "other")
    ex[key] = ex.get(key, 0) + 1


def symbol_multiplier(state, symbol):
    """Score multiplier from a symbol's realized win-rate (0.5..1.5), or 1.0
    until it has enough closed trades to judge."""
    s = (state.get("perf") or {}).get(symbol)
    if not s:
        return 1.0
    n = s["wins"] + s["losses"]
    if n < MIN_TRADES_FOR_WEIGHT:
        return 1.0
    return round(0.5 + s["wins"] / n, 3)


def perf_summary(state):
    perf = state.get("perf") or {}
    out = []
    for sym, s in perf.items():
        n = s["wins"] + s["losses"]
        if n:
            out.append(f"{finnhub_data.ticker_of(sym)} {s['wins']}/{n} "
                       f"pnl {s['pnl']:+.2f}")
    return out


# ----------------------- Level 2: adaptive exits -----------------------
def adaptive_exits(state, base_stop, base_tp):
    """Tune the stop based on how often stops vs take-profits fire recently."""
    ex = state.get("exit_stats") or {}
    stops, tps = ex.get("stop", 0), ex.get("tp", 0)
    total = stops + tps
    stop = base_stop
    if total >= 10:
        stop_rate = stops / total
        if stop_rate > 0.6:                       # whipsawed -> widen the stop
            stop = min(base_stop * 1.4, base_stop + 2.0)
        elif stop_rate < 0.3:                     # rarely stopped -> tighten a bit
            stop = max(base_stop * 0.85, 1.0)
    return round(stop, 2), round(base_tp, 2)


# ----------------------- Level 3: ML coach -----------------------
def _vol(closes, i, n=10):
    if i < n:
        return 0.0
    rets = [closes[j] / closes[j - 1] - 1.0 for j in range(i - n + 1, i + 1)
            if closes[j - 1]]
    if len(rets) < 2:
        return 0.0
    m = sum(rets) / len(rets)
    return (sum((x - m) ** 2 for x in rets) / len(rets)) ** 0.5


def _feats(closes, i, sma50, sma200, rsi):
    """Entry-context features at bar i (same in training and live)."""
    if i < 60 or sma50[i] is None or rsi[i] is None:
        return None
    price = closes[i]
    if price == 0 or sma50[i] == 0:
        return None

    def r(n):
        return price / closes[i - n] - 1.0 if i >= n and closes[i - n] else 0.0
    s200 = sma200[i]
    return [r(5), r(21), r(63), rsi[i] / 100.0,
            price / sma50[i] - 1.0,
            (price / s200 - 1.0) if s200 else 0.0,
            _vol(closes, i)]


def _label(closes, i, tp, sl, h=H):
    """1 if the trade would hit +tp% before -sl% within h bars, else 0."""
    entry = closes[i]
    if entry == 0:
        return 0
    for j in range(i + 1, min(i + h + 1, len(closes))):
        ch = closes[j] / entry - 1.0
        if ch >= tp / 100.0:
            return 1
        if ch <= -sl / 100.0:
            return 0
    last = closes[min(i + h, len(closes) - 1)]
    return 1 if last >= entry else 0


def build_training_data(symbols, tp, sl):
    X, y = [], []
    for sym in symbols:
        closes = market.stock_daily_closes(finnhub_data.ticker_of(sym))
        if len(closes) < 120:
            continue
        sma50 = sma_series(closes, 50)
        sma200 = sma_series(closes, 200)
        rsi = rsi_series(closes, 14)
        for i in range(60, len(closes) - 1):
            f = _feats(closes, i, sma50, sma200, rsi)
            if f is None:
                continue
            X.append(f)
            y.append(_label(closes, i, tp, sl))
    return X, y


def train(symbols, tp, sl):
    """Train the coach on back-tested trades. Returns {samples, val_acc} or None."""
    if not HAVE_SK:
        return None
    X, y = build_training_data(symbols, tp, sl)
    if len(X) < MIN_SAMPLES or len(set(y)) < 2:
        return None
    try:
        k = int(len(X) * 0.8)
        clf = GradientBoostingClassifier(
            n_estimators=120, max_depth=3, learning_rate=0.05, random_state=0)
        clf.fit(np.array(X[:k]), np.array(y[:k]))
        acc = (round(float(clf.score(np.array(X[k:]), np.array(y[k:]))), 3)
               if len(X) - k >= 20 else None)
        _model[0] = (clf, len(X))
        MODELS_DIR.mkdir(exist_ok=True)
        try:
            import joblib
            joblib.dump(clf, MODELS_DIR / "coach.pkl")
        except Exception:
            pass
        return {"samples": len(X), "val_acc": acc}
    except Exception:
        return None


def _load():
    if _model[0]:
        return _model[0][0]
    try:
        import joblib
        p = MODELS_DIR / "coach.pkl"
        if p.exists():
            clf = joblib.load(p)
            _model[0] = (clf, 0)
            return clf
    except Exception:
        pass
    return None


def win_probability(symbol):
    """Estimated probability (0..1) a fresh entry on ``symbol`` wins, or None."""
    if not HAVE_SK:
        return None
    clf = _load()
    if clf is None:
        return None
    closes = market.stock_daily_closes(finnhub_data.ticker_of(symbol))
    if len(closes) < 61:
        return None
    sma50 = sma_series(closes, 50)
    sma200 = sma_series(closes, 200)
    rsi = rsi_series(closes, 14)
    f = _feats(closes, len(closes) - 1, sma50, sma200, rsi)
    if f is None:
        return None
    try:
        return round(float(clf.predict_proba(np.array([f]))[0][1]), 3)
    except Exception:
        return None
